url: 'https://shadbags.github.io'
baseurl: 'Godot-Platformer-Tutorial'
title: 'Jekyllwind'

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - package-lock.json
  
